method: vnn_onet
data:
  input_type: pointcloud
  path: data/ShapeNet
  pointcloud_n: 300
  pointcloud_noise: 0.005
  points_subsample: 2048
  rotation_path: data_rotations/ShapeNet
  rotation_augment: so3
model:
  encoder_latent: null
  decoder: simple_inner
  encoder: vnn_pointnet_resnet
  encoder_kwargs:
    hidden_dim: 342
  c_dim: 171
  z_dim: 0
training:
  out_dir: results/equinet/vnn_pointnet_resnet_so3
  batch_size: 64
  model_selection_metric: iou
  model_selection_mode: maximize
  latent_reg: null
  latent_reg_scale: 0.0
test:
  threshold: 0.2
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1